### PR TITLE
Creating Resources Guide

### LINKED ISSUE #469: Update Element Mapper (Transformations) Guide
## Description
As a user of Cloud Elements, I need detailed instructions to create transformations.

In general, the steps will be:
- [x] Assess the current state of the Transformations Guide.
- [x] Create a simple documentation plan to update the guide (this).
- [x] Create new issues and add to epic.
- [x] Identify how to distinguish between C2 and C1.
- [x] Identify timeline needed to support both versions. 
- [x] Write content for Create via UI (in C2). #515 
- [x] Write Definitions section for C2. #386
- [x] Write Overview section for C2. #386 
- [ ] Add Element Mapper Load Metadata by ID functionality #493
- [x] Write content for Create via API. #516
- [x] Write Mapping complex Objects content C1 and C2: #388 and #389 
- [ ] Write Management and FAQ content (C2). #517
- [ ] Review and create links (C2). #518
- [x] Assess C2 content for how it affects C1. #519
- [x] Update C1 content as needed. #563 
- [ ] Write migration content for users moving from C1 to C2.#520
- [ ] Send for review

### PR DESCRIPTION
**Pull request by davewilks**
## Highlights
* Whole new list of files under the common-resources directory
* Support files for glossary and notes
* css updates

## Closes
* Closes #469

### CODE REVIEW

**Comment by jjwyse** [comment]
@davewilks - about to start reviewing.  no rush, but can you handle the above conflicts when you get a second too.  thanks!

**Comment by davewilks** [comment]
Conflicts resolved, @jjwyse it's all yours.

**Comment by davewilks** [comment]
@jjwyse Great review. I'll get to it shortly.

**Comment by davewilks** [comment]
I added @jjwyse changes, resolved some conflicts, and think it's ready to go. I think I was able to update the format correctly on all of the JSON throughout. Let me know if you see anything else.

@claytonshaver have a look also.

**Pull request merged**
